Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sweep_table = load_sweep_table(s3_url)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn [7], line 1[0m
[0;32m----> 1[0m sweep_table [38;5;241m=[39m load_sweep_table(s3_url)

Cell [0;32mIn [6], line 3[0m, in [0;36mload_sweep_table[0;34m(s3_url)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mload_sweep_table[39m(s3_url):
[1;32m      2[0m     [38;5;124;03m'''Creates a dataframe of the stimulus presentation table'''[39;00m
[0;32m----> 3[0m     [38;5;28;01mwith[39;00m [43mpynwb[49m[38;5;241;43m.[39;49m[43mNWBHDF5IO[49m[43m([49m[43ms3_url[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mload_namespaces[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mdriver[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mros3[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m io:
[1;32m      4[0m         nwbfile [38;5;241m=[39m io[38;5;241m.[39mread()
[1;32m      5[0m         start_times [38;5;241m=[39m np[38;5;241m.[39marray(nwbfile[38;5;241m.[39mintervals[[38;5;124m'[39m[38;5;124mepochs[39m[38;5;124m'[39m][[38;5;124m'[39m[38;5;124mstart_time[39m[38;5;124m'[39m][38;5;241m.[39mdata)

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/utils.py:645[0m, in [0;36mdocval.<locals>.dec.<locals>.func_call[0;34m(*args, **kwargs)[0m
[1;32m    643[0m [38;5;28;01mdef[39;00m [38;5;21mfunc_call[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    644[0m     pargs [38;5;241m=[39m _check_args(args, kwargs)
[0;32m--> 645[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43margs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mpargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pynwb/__init__.py:230[0m, in [0;36mNWBHDF5IO.__init__[0;34m(self, **kwargs)[0m
[1;32m    227[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mcannot load namespaces from file when writing to it[39m[38;5;124m"[39m)
[1;32m    229[0m     tm [38;5;241m=[39m get_type_map()
[0;32m--> 230[0m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mload_namespaces[49m[43m([49m[43mtm[49m[43m,[49m[43m [49m[43mpath[49m[43m,[49m[43m [49m[43mfile[49m[38;5;241;43m=[39;49m[43mfile_obj[49m[43m,[49m[43m [49m[43mdriver[49m[38;5;241;43m=[39;49m[43mdriver[49m[43m)[49m
[1;32m    231[0m     manager [38;5;241m=[39m BuildManager(tm)
[1;32m    233[0m     [38;5;66;03m# XXX: Leaving this here in case we want to revert to this strategy for[39;00m
[1;32m    234[0m     [38;5;66;03m#      loading cached namespaces[39;00m
[1;32m    235[0m     [38;5;66;03m# ns_catalog = NamespaceCatalog(NWBGroupSpec, NWBDatasetSpec, NWBNamespace)[39;00m
[0;32m   (...)[0m
[1;32m    238[0m     [38;5;66;03m# tm.copy_mappers(get_type_map())[39;00m
[1;32m    239[0m [38;5;28;01melse[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/utils.py:645[0m, in [0;36mdocval.<locals>.dec.<locals>.func_call[0;34m(*args, **kwargs)[0m
[1;32m    643[0m [38;5;28;01mdef[39;00m [38;5;21mfunc_call[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    644[0m     pargs [38;5;241m=[39m _check_args(args, kwargs)
[0;32m--> 645[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43margs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mpargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py:150[0m, in [0;36mHDF5IO.load_namespaces[0;34m(cls, **kwargs)[0m
[1;32m    139[0m [38;5;124;03m"""Load cached namespaces from a file.[39;00m
[1;32m    140[0m 
[1;32m    141[0m [38;5;124;03mIf `file` is not supplied, then an :py:class:`h5py.File` object will be opened for the given `path`, the[39;00m
[0;32m   (...)[0m
[1;32m    145[0m [38;5;124;03m:raises ValueError: if both `path` and `file` are supplied but `path` is not the same as the path of `file`.[39;00m
[1;32m    146[0m [38;5;124;03m"""[39;00m
[1;32m    147[0m namespace_catalog, path, namespaces, file_obj, driver [38;5;241m=[39m popargs(
[1;32m    148[0m     [38;5;124m'[39m[38;5;124mnamespace_catalog[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mpath[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnamespaces[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mfile[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdriver[39m[38;5;124m'[39m, kwargs)
[0;32m--> 150[0m open_file_obj [38;5;241m=[39m [38;5;28;43mcls[39;49m[38;5;241;43m.[39;49m[43m__resolve_file_obj[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mfile_obj[49m[43m,[49m[43m [49m[43mdriver[49m[43m)[49m
[1;32m    151[0m [38;5;28;01mif[39;00m file_obj [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# need to close the file object that we just opened[39;00m
[1;32m    152[0m     [38;5;28;01mwith[39;00m open_file_obj:

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py:125[0m, in [0;36mHDF5IO.__resolve_file_obj[0;34m(path, file_obj, driver)[0m
[1;32m    123[0m     [38;5;28;01mif[39;00m driver [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    124[0m         file_kwargs[38;5;241m.[39mupdate(driver[38;5;241m=[39mdriver)
[0;32m--> 125[0m     file_obj [38;5;241m=[39m [43mFile[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfile_kwargs[49m[43m)[49m
[1;32m    126[0m [38;5;28;01mreturn[39;00m file_obj

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/h5py/_hl/files.py:485[0m, in [0;36mFile.__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, **kwds)[0m
[1;32m    482[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mThe SWMR feature is not available in this version of the HDF5 library[39m[38;5;124m"[39m)
[1;32m    484[0m [38;5;28;01mif[39;00m driver [38;5;241m==[39m [38;5;124m'[39m[38;5;124mros3[39m[38;5;124m'[39m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m ros3:
[0;32m--> 485[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    486[0m         [38;5;124m"[39m[38;5;124mh5py was built without ROS3 support, can[39m[38;5;124m'[39m[38;5;124mt use ros3 driver[39m[38;5;124m"[39m)
[1;32m    488[0m [38;5;28;01mif[39;00m locking [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m hdf5_version [38;5;241m<[39m ([38;5;241m1[39m, [38;5;241m12[39m, [38;5;241m1[39m) [38;5;129;01mand[39;00m (
[1;32m    489[0m         hdf5_version[:[38;5;241m2[39m] [38;5;241m!=[39m ([38;5;241m1[39m, [38;5;241m10[39m) [38;5;129;01mor[39;00m hdf5_version[[38;5;241m2[39m] [38;5;241m<[39m [38;5;241m7[39m):
[1;32m    490[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mHDF version >= 1.12.1 or 1.10.x >= 1.10.7 required for file locking options.[39m[38;5;124m"[39m)

[0;31mValueError[0m: h5py was built without ROS3 support, can't use ros3 driver
ValueError: h5py was built without ROS3 support, can't use ros3 driver

